# Use this Blueprint to deploy n8n on Render as a web
# service that uses a Postgres database to store
# workflow data.
#
# This Blueprint uses free instance types (specified by
# `plan`) for both the web service and the database. You
# can upgrade to paid instance types at any time to
# increase resources.

services:
  - type: web
    plan: free
    # This is the runtime for services that pull a prebuilt Docker image
    runtime: image
    # You can give the service any name
    name: n8n-service
    image:
      # Pulls the n8n image tagged as latest from Docker Hub
      url: docker.io/n8nio/n8n:latest

databases:
  - name: n8n-db
    plan: free
